### PR TITLE
Scala 2.12.10 and 2.13.1

### PR DESCRIPTION
**Pull request by ennru**

### CODE REVIEW

**Comment by ennru** [comment]
I'm not sure about some of the Lagom dependencies for Scala 2.13
```
com.lightbend.lagom#lagom-scaladsl-persistence_2.13;1.5.4: not found
com.lightbend.lagom#lagom-javadsl-persistence_2.13;1.5.4: not found
com.lightbend.lagom#lagom-persistence-core_2.13;1.5.4: not found
```
cc @ignasi35 @renatocaval

**Comment by ignasi35** [comment]
There's no [support for scala 2.13 in Lagom until `1.6.0-M4`](https://github.com/lagom/lagom/issues/1240)

**Comment by ignasi35** [comment]
More: https://search.maven.org/search?q=g:com.lightbend.lagom%20AND%20a:lagom-scaladsl-persistence_2.13&core=gav

**Comment by ennru** [comment]
Thank you, that's what I thought. I created #229 to be followed up after the upcoming releases.

**Comment by ignasi35** [comment]
superseded by #234

**Pull request closed without merging**
